#!/usr/bin/env bash

# Check if the bucket name is provided
if [ -z "$1" ]; then
    echo "Please provide a bucket name as an argument."
    exit 1
fi

# Assign bucket name and region
BUCKET_NAME=$1
REGION="ap-south-1" # Set the desired region here

# Create the bucket with region configuration
aws s3api delete-bucket --bucket "$BUCKET_NAME"

# Check if bucket creation succeeded
if [ $? -eq 0 ]; then
    echo "Bucket '$BUCKET_NAME' deleted successfully in region '$REGION'."
else
    echo "Failed to create bucket '$BUCKET_NAME'."
    exit 1
fi
